/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: accelerationForce.proto */

#ifndef PROTOBUF_C_accelerationForce_2eproto__INCLUDED
#define PROTOBUF_C_accelerationForce_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003000 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _Navirice__Proto__AccelerationForce Navirice__Proto__AccelerationForce;


/* --- enums --- */


/* --- messages --- */

struct  _Navirice__Proto__AccelerationForce
{
  ProtobufCMessage base;
  float x;
  float y;
  float z;
};
#define NAVIRICE__PROTO__ACCELERATION_FORCE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&navirice__proto__acceleration_force__descriptor) \
    , 0, 0, 0 }


/* Navirice__Proto__AccelerationForce methods */
void   navirice__proto__acceleration_force__init
                     (Navirice__Proto__AccelerationForce         *message);
size_t navirice__proto__acceleration_force__get_packed_size
                     (const Navirice__Proto__AccelerationForce   *message);
size_t navirice__proto__acceleration_force__pack
                     (const Navirice__Proto__AccelerationForce   *message,
                      uint8_t             *out);
size_t navirice__proto__acceleration_force__pack_to_buffer
                     (const Navirice__Proto__AccelerationForce   *message,
                      ProtobufCBuffer     *buffer);
Navirice__Proto__AccelerationForce *
       navirice__proto__acceleration_force__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   navirice__proto__acceleration_force__free_unpacked
                     (Navirice__Proto__AccelerationForce *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Navirice__Proto__AccelerationForce_Closure)
                 (const Navirice__Proto__AccelerationForce *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor navirice__proto__acceleration_force__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_accelerationForce_2eproto__INCLUDED */
