/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: accelerationForce.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "accelerationForce.pb-c.h"
void   navirice__proto__acceleration_force__init
                     (Navirice__Proto__AccelerationForce         *message)
{
  static const Navirice__Proto__AccelerationForce init_value = NAVIRICE__PROTO__ACCELERATION_FORCE__INIT;
  *message = init_value;
}
size_t navirice__proto__acceleration_force__get_packed_size
                     (const Navirice__Proto__AccelerationForce *message)
{
  assert(message->base.descriptor == &navirice__proto__acceleration_force__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t navirice__proto__acceleration_force__pack
                     (const Navirice__Proto__AccelerationForce *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &navirice__proto__acceleration_force__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t navirice__proto__acceleration_force__pack_to_buffer
                     (const Navirice__Proto__AccelerationForce *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &navirice__proto__acceleration_force__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Navirice__Proto__AccelerationForce *
       navirice__proto__acceleration_force__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Navirice__Proto__AccelerationForce *)
     protobuf_c_message_unpack (&navirice__proto__acceleration_force__descriptor,
                                allocator, len, data);
}
void   navirice__proto__acceleration_force__free_unpacked
                     (Navirice__Proto__AccelerationForce *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &navirice__proto__acceleration_force__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor navirice__proto__acceleration_force__field_descriptors[3] =
{
  {
    "x",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Navirice__Proto__AccelerationForce, x),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "y",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Navirice__Proto__AccelerationForce, y),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "z",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Navirice__Proto__AccelerationForce, z),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned navirice__proto__acceleration_force__field_indices_by_name[] = {
  0,   /* field[0] = x */
  1,   /* field[1] = y */
  2,   /* field[2] = z */
};
static const ProtobufCIntRange navirice__proto__acceleration_force__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor navirice__proto__acceleration_force__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "navirice.proto.AccelerationForce",
  "AccelerationForce",
  "Navirice__Proto__AccelerationForce",
  "navirice.proto",
  sizeof(Navirice__Proto__AccelerationForce),
  3,
  navirice__proto__acceleration_force__field_descriptors,
  navirice__proto__acceleration_force__field_indices_by_name,
  1,  navirice__proto__acceleration_force__number_ranges,
  (ProtobufCMessageInit) navirice__proto__acceleration_force__init,
  NULL,NULL,NULL    /* reserved[123] */
};
