/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: location.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "location.pb-c.h"
void   navirice__proto__location__init
                     (Navirice__Proto__Location         *message)
{
  static const Navirice__Proto__Location init_value = NAVIRICE__PROTO__LOCATION__INIT;
  *message = init_value;
}
size_t navirice__proto__location__get_packed_size
                     (const Navirice__Proto__Location *message)
{
  assert(message->base.descriptor == &navirice__proto__location__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t navirice__proto__location__pack
                     (const Navirice__Proto__Location *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &navirice__proto__location__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t navirice__proto__location__pack_to_buffer
                     (const Navirice__Proto__Location *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &navirice__proto__location__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Navirice__Proto__Location *
       navirice__proto__location__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Navirice__Proto__Location *)
     protobuf_c_message_unpack (&navirice__proto__location__descriptor,
                                allocator, len, data);
}
void   navirice__proto__location__free_unpacked
                     (Navirice__Proto__Location *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &navirice__proto__location__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor navirice__proto__location__field_descriptors[2] =
{
  {
    "latitude",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(Navirice__Proto__Location, latitude),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "longitude",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(Navirice__Proto__Location, longitude),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned navirice__proto__location__field_indices_by_name[] = {
  0,   /* field[0] = latitude */
  1,   /* field[1] = longitude */
};
static const ProtobufCIntRange navirice__proto__location__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor navirice__proto__location__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "navirice.proto.Location",
  "Location",
  "Navirice__Proto__Location",
  "navirice.proto",
  sizeof(Navirice__Proto__Location),
  2,
  navirice__proto__location__field_descriptors,
  navirice__proto__location__field_indices_by_name,
  1,  navirice__proto__location__number_ranges,
  (ProtobufCMessageInit) navirice__proto__location__init,
  NULL,NULL,NULL    /* reserved[123] */
};
