/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: location.proto */

#ifndef PROTOBUF_C_location_2eproto__INCLUDED
#define PROTOBUF_C_location_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003000 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _Navirice__Proto__Location Navirice__Proto__Location;


/* --- enums --- */


/* --- messages --- */

struct  _Navirice__Proto__Location
{
  ProtobufCMessage base;
  double latitude;
  double longitude;
};
#define NAVIRICE__PROTO__LOCATION__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&navirice__proto__location__descriptor) \
    , 0, 0 }


/* Navirice__Proto__Location methods */
void   navirice__proto__location__init
                     (Navirice__Proto__Location         *message);
size_t navirice__proto__location__get_packed_size
                     (const Navirice__Proto__Location   *message);
size_t navirice__proto__location__pack
                     (const Navirice__Proto__Location   *message,
                      uint8_t             *out);
size_t navirice__proto__location__pack_to_buffer
                     (const Navirice__Proto__Location   *message,
                      ProtobufCBuffer     *buffer);
Navirice__Proto__Location *
       navirice__proto__location__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   navirice__proto__location__free_unpacked
                     (Navirice__Proto__Location *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Navirice__Proto__Location_Closure)
                 (const Navirice__Proto__Location *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor navirice__proto__location__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_location_2eproto__INCLUDED */
