/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: requestHeader.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "requestHeader.pb-c.h"
void   navirice__proto__request_header__init
                     (Navirice__Proto__RequestHeader         *message)
{
  static const Navirice__Proto__RequestHeader init_value = NAVIRICE__PROTO__REQUEST_HEADER__INIT;
  *message = init_value;
}
size_t navirice__proto__request_header__get_packed_size
                     (const Navirice__Proto__RequestHeader *message)
{
  assert(message->base.descriptor == &navirice__proto__request_header__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t navirice__proto__request_header__pack
                     (const Navirice__Proto__RequestHeader *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &navirice__proto__request_header__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t navirice__proto__request_header__pack_to_buffer
                     (const Navirice__Proto__RequestHeader *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &navirice__proto__request_header__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Navirice__Proto__RequestHeader *
       navirice__proto__request_header__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Navirice__Proto__RequestHeader *)
     protobuf_c_message_unpack (&navirice__proto__request_header__descriptor,
                                allocator, len, data);
}
void   navirice__proto__request_header__free_unpacked
                     (Navirice__Proto__RequestHeader *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &navirice__proto__request_header__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCEnumValue navirice__proto__request_header__type__enum_values_by_number[4] =
{
  { "CURRENT_STEP", "NAVIRICE__PROTO__REQUEST_HEADER__TYPE__CURRENT_STEP", 0 },
  { "CURRENT_LOCATION", "NAVIRICE__PROTO__REQUEST_HEADER__TYPE__CURRENT_LOCATION", 1 },
  { "CURRENT_ACCELERATION_FORCE", "NAVIRICE__PROTO__REQUEST_HEADER__TYPE__CURRENT_ACCELERATION_FORCE", 2 },
  { "CURRENT_ROTATION_RATE", "NAVIRICE__PROTO__REQUEST_HEADER__TYPE__CURRENT_ROTATION_RATE", 3 },
};
static const ProtobufCIntRange navirice__proto__request_header__type__value_ranges[] = {
{0, 0},{0, 4}
};
static const ProtobufCEnumValueIndex navirice__proto__request_header__type__enum_values_by_name[4] =
{
  { "CURRENT_ACCELERATION_FORCE", 2 },
  { "CURRENT_LOCATION", 1 },
  { "CURRENT_ROTATION_RATE", 3 },
  { "CURRENT_STEP", 0 },
};
const ProtobufCEnumDescriptor navirice__proto__request_header__type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "navirice.proto.RequestHeader.Type",
  "Type",
  "Navirice__Proto__RequestHeader__Type",
  "navirice.proto",
  4,
  navirice__proto__request_header__type__enum_values_by_number,
  4,
  navirice__proto__request_header__type__enum_values_by_name,
  1,
  navirice__proto__request_header__type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor navirice__proto__request_header__field_descriptors[2] =
{
  {
    "type",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Navirice__Proto__RequestHeader, type),
    &navirice__proto__request_header__type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "length",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Navirice__Proto__RequestHeader, length),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned navirice__proto__request_header__field_indices_by_name[] = {
  1,   /* field[1] = length */
  0,   /* field[0] = type */
};
static const ProtobufCIntRange navirice__proto__request_header__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor navirice__proto__request_header__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "navirice.proto.RequestHeader",
  "RequestHeader",
  "Navirice__Proto__RequestHeader",
  "navirice.proto",
  sizeof(Navirice__Proto__RequestHeader),
  2,
  navirice__proto__request_header__field_descriptors,
  navirice__proto__request_header__field_indices_by_name,
  1,  navirice__proto__request_header__number_ranges,
  (ProtobufCMessageInit) navirice__proto__request_header__init,
  NULL,NULL,NULL    /* reserved[123] */
};
