/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: response.proto */

#ifndef PROTOBUF_C_response_2eproto__INCLUDED
#define PROTOBUF_C_response_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003000 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _Navirice__Proto__Response Navirice__Proto__Response;


/* --- enums --- */

typedef enum _Navirice__Proto__Response__Status {
  NAVIRICE__PROTO__RESPONSE__STATUS__SUCCESS = 0,
  NAVIRICE__PROTO__RESPONSE__STATUS__BAD_REQUEST = 1,
  NAVIRICE__PROTO__RESPONSE__STATUS__NOT_IMPLEMENTED = 2
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(NAVIRICE__PROTO__RESPONSE__STATUS)
} Navirice__Proto__Response__Status;

/* --- messages --- */

struct  _Navirice__Proto__Response
{
  ProtobufCMessage base;
  Navirice__Proto__Response__Status status;
};
#define NAVIRICE__PROTO__RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&navirice__proto__response__descriptor) \
    , NAVIRICE__PROTO__RESPONSE__STATUS__SUCCESS }


/* Navirice__Proto__Response methods */
void   navirice__proto__response__init
                     (Navirice__Proto__Response         *message);
size_t navirice__proto__response__get_packed_size
                     (const Navirice__Proto__Response   *message);
size_t navirice__proto__response__pack
                     (const Navirice__Proto__Response   *message,
                      uint8_t             *out);
size_t navirice__proto__response__pack_to_buffer
                     (const Navirice__Proto__Response   *message,
                      ProtobufCBuffer     *buffer);
Navirice__Proto__Response *
       navirice__proto__response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   navirice__proto__response__free_unpacked
                     (Navirice__Proto__Response *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Navirice__Proto__Response_Closure)
                 (const Navirice__Proto__Response *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor navirice__proto__response__descriptor;
extern const ProtobufCEnumDescriptor    navirice__proto__response__status__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_response_2eproto__INCLUDED */
