/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: rotationRate.proto */

#ifndef PROTOBUF_C_rotationRate_2eproto__INCLUDED
#define PROTOBUF_C_rotationRate_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003000 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _Navirice__Proto__RotationRate Navirice__Proto__RotationRate;


/* --- enums --- */


/* --- messages --- */

struct  _Navirice__Proto__RotationRate
{
  ProtobufCMessage base;
  float x;
  float y;
  float z;
};
#define NAVIRICE__PROTO__ROTATION_RATE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&navirice__proto__rotation_rate__descriptor) \
    , 0, 0, 0 }


/* Navirice__Proto__RotationRate methods */
void   navirice__proto__rotation_rate__init
                     (Navirice__Proto__RotationRate         *message);
size_t navirice__proto__rotation_rate__get_packed_size
                     (const Navirice__Proto__RotationRate   *message);
size_t navirice__proto__rotation_rate__pack
                     (const Navirice__Proto__RotationRate   *message,
                      uint8_t             *out);
size_t navirice__proto__rotation_rate__pack_to_buffer
                     (const Navirice__Proto__RotationRate   *message,
                      ProtobufCBuffer     *buffer);
Navirice__Proto__RotationRate *
       navirice__proto__rotation_rate__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   navirice__proto__rotation_rate__free_unpacked
                     (Navirice__Proto__RotationRate *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Navirice__Proto__RotationRate_Closure)
                 (const Navirice__Proto__RotationRate *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor navirice__proto__rotation_rate__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_rotationRate_2eproto__INCLUDED */
