/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: step.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "step.pb-c.h"
void   navirice__proto__step__init
                     (Navirice__Proto__Step         *message)
{
  static const Navirice__Proto__Step init_value = NAVIRICE__PROTO__STEP__INIT;
  *message = init_value;
}
size_t navirice__proto__step__get_packed_size
                     (const Navirice__Proto__Step *message)
{
  assert(message->base.descriptor == &navirice__proto__step__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t navirice__proto__step__pack
                     (const Navirice__Proto__Step *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &navirice__proto__step__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t navirice__proto__step__pack_to_buffer
                     (const Navirice__Proto__Step *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &navirice__proto__step__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Navirice__Proto__Step *
       navirice__proto__step__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Navirice__Proto__Step *)
     protobuf_c_message_unpack (&navirice__proto__step__descriptor,
                                allocator, len, data);
}
void   navirice__proto__step__free_unpacked
                     (Navirice__Proto__Step *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &navirice__proto__step__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor navirice__proto__step__field_descriptors[4] =
{
  {
    "latitude",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(Navirice__Proto__Step, latitude),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "longitude",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(Navirice__Proto__Step, longitude),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "description",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Navirice__Proto__Step, description),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "icon",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Navirice__Proto__Step, icon),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned navirice__proto__step__field_indices_by_name[] = {
  2,   /* field[2] = description */
  3,   /* field[3] = icon */
  0,   /* field[0] = latitude */
  1,   /* field[1] = longitude */
};
static const ProtobufCIntRange navirice__proto__step__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor navirice__proto__step__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "navirice.proto.Step",
  "Step",
  "Navirice__Proto__Step",
  "navirice.proto",
  sizeof(Navirice__Proto__Step),
  4,
  navirice__proto__step__field_descriptors,
  navirice__proto__step__field_indices_by_name,
  1,  navirice__proto__step__number_ranges,
  (ProtobufCMessageInit) navirice__proto__step__init,
  NULL,NULL,NULL    /* reserved[123] */
};
