/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: step.proto */

#ifndef PROTOBUF_C_step_2eproto__INCLUDED
#define PROTOBUF_C_step_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003000 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _Navirice__Proto__Step Navirice__Proto__Step;


/* --- enums --- */


/* --- messages --- */

struct  _Navirice__Proto__Step
{
  ProtobufCMessage base;
  double latitude;
  double longitude;
  char *description;
  char *icon;
};
#define NAVIRICE__PROTO__STEP__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&navirice__proto__step__descriptor) \
    , 0, 0, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string }


/* Navirice__Proto__Step methods */
void   navirice__proto__step__init
                     (Navirice__Proto__Step         *message);
size_t navirice__proto__step__get_packed_size
                     (const Navirice__Proto__Step   *message);
size_t navirice__proto__step__pack
                     (const Navirice__Proto__Step   *message,
                      uint8_t             *out);
size_t navirice__proto__step__pack_to_buffer
                     (const Navirice__Proto__Step   *message,
                      ProtobufCBuffer     *buffer);
Navirice__Proto__Step *
       navirice__proto__step__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   navirice__proto__step__free_unpacked
                     (Navirice__Proto__Step *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Navirice__Proto__Step_Closure)
                 (const Navirice__Proto__Step *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor navirice__proto__step__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_step_2eproto__INCLUDED */
